In [4]:
import numpy as np
import pandas as pd
import datetime
import math

In [8]:
daily=pd.read_csv('dam_daily.csv')
daily

,year,month,day,volume,value,price_weight_av,price_mean,off_price_mean,standard_price_mean,morning_price_mean,evening_price_mean,off_hour_count,standard_hour_count,morning_hour_count,evening_hour_count,off_volume,standard_volume,morning_volume,evening_volume
0,2016,1,1,7873.8,336882.508,42.785251,45.982500,45.982500,NaN,NaN,NaN,24,NaN,NaN,NaN,7873.8,NaN,NaN,NaN
1,2016,1,2,7319.5,345982.021,47.268532,54.114167,45.511333,68.452222,NaN,NaN,15,9.0,NaN,NaN,5994.5,1325.0,NaN,NaN
2,2016,1,3,7198.7,351712.733,48.857812,54.959167,48.152222,75.380000,NaN,NaN,18,6.0,NaN,NaN,6607.3,591.4,NaN,NaN
3,2016,1,4,4457.0,225938.810,50.693024,80.164583,47.992222,80.720833,NaN,174.456667,9,12.0,NaN,3.0,4028.0,429.0,NaN,0.0
4,2016,1,5,3750.4,179068.882,47.746609,84.503333,43.756667,93.589167,148.400,181.400000,9,12.0,1.0,2.0,3380.0,370.4,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1942,2021,4,26,2092.9,185605.239,88.683281,102.215000,42.868889,96.981818,201.055,299.215000,9,11.0,2.0,2.0,789.4,1065.1,144.3,94.1
1943,2021,4,27,2048.2,168261.497,82.150912,94.468333,42.197778,80.660000,201.015,299.085000,9,11.0,2.0,2.0,947.8,856.0,134.7,109.7
1944,2021,4,28,2130.2,177543.993,83.346161,100.343333,42.605556,95.224545,189.575,299.085000,9,11.0,2.0,2.0,1095.8,788.4,136.0,110.0
1945,2021,4,29,2134.0,178697.984,83.738512,98.742500,42.532222,92.590909,187.460,296.805000,9,11.0,2.0,2.0,1100.0,772.0,142.0,120.0
1946,2021,4,30,2198.9,187057.475,85.068659,98.218750,42.047778,92.895455,182.510,295.975000,9,11.0,2.0,2.0,912.7,1022.2,144.0,120.0

In [12]:
monthly=daily.groupby(['year','month']).mean().reset_index(['month','year'])
monthly=monthly.drop(['morning_volume','off_volume','standard_volume'],1)
monthly.rename(columns={'value':'value_mean','volume':'volume_mean','price_weight_av': 'price_weight_mean','off_hour_count':'off_hour_mean','standard_hour_count':'standard_hour_mean','morning_hour_count':'morning_hour_mean','evening_hour_count':'evening_hour_mean'}, inplace=True)
monthly[['price_max','standard_price_max','off_price_max','morning_price_max','evening_price_max']]=daily.groupby(['year','month']).max().reset_index(['month','year'])[['price_mean','standard_price_mean','off_price_mean','morning_price_mean','evening_price_mean']]
monthly[['price_min','standard_price_min','off_price_min','morning_price_min','evening_price_min']]=daily.groupby(['year','month']).min().reset_index(['month','year'])[['price_mean','standard_price_mean','off_price_mean','morning_price_mean','evening_price_mean']]
monthly[['off_price_stdev','morning_price_stdev','standard_price_stdev','evening_price_stdev']]=daily.groupby(['year','month']).std().reset_index(['month','year'])[['off_price_mean','morning_price_mean','standard_price_mean','evening_price_mean']]
monthly[['volume','value','morning_volume','evening_volume','standard_volume','off_volume']]=daily.groupby(['year','month']).sum().reset_index(['month','year'])[['volume','value','morning_volume','evening_volume','standard_volume','off_volume']]


monthly

,year,month,day,volume_mean,value_mean,price_weight_mean,price_mean,off_price_mean,standard_price_mean,morning_price_mean,...,standard_price_min,off_price_min,morning_price_min,evening_price_min,morning_price_stdev,volume,value,morning_volume,standard_volume,off_volume
0,2016,1,16.0,3877.909677,216538.697903,57.486909,81.784624,50.482142,100.237891,146.915000,...,68.452222,43.144444,113.860000,113.970000,12.254047,120215.2,6712699.635,405.6,14040.7,103877.5
1,2016,2,15.0,3915.110345,263339.799483,67.019849,91.385273,51.665330,102.343821,137.159365,...,86.090000,50.480000,110.718000,110.686000,7.789197,113538.2,7636854.185,2118.5,25701.0,80348.6
2,2016,3,16.0,3004.254839,192831.319548,63.764714,88.099516,51.887979,98.659245,124.078913,...,74.171429,50.518750,95.855000,110.043333,11.776869,93131.9,5977770.906,3143.0,17821.8,68386.2
3,2016,4,15.5,1934.450000,119384.364433,59.168072,85.320472,45.608219,97.839609,130.572500,...,55.706471,0.000000,105.530000,114.663000,18.774919,58033.5,3581530.933,1094.6,13598.8,42693.7
4,2016,5,16.0,1714.970968,95755.502839,51.079876,78.638495,43.121126,99.223370,133.084917,...,45.162000,24.316842,106.200000,102.150000,22.146905,53164.1,2968420.588,871.7,6354.3,45201.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,2020,12,16.0,2765.732258,215368.490710,81.531884,87.973105,50.377869,107.096349,147.206212,...,73.705714,45.683750,92.100000,160.030000,17.716296,85737.7,6676423.212,6258.0,20196.2,56545.1
60,2021,1,16.0,2506.932258,151566.968968,60.267025,63.961895,50.870766,79.474182,98.463860,...,60.162000,44.061818,96.700000,95.067500,18.802658,77714.9,4698576.038,4879.0,16883.5,53567.0
61,2021,2,14.5,2225.446429,183252.046929,83.585698,84.913795,53.185476,111.021325,172.972292,...,72.030000,43.510417,96.763333,123.676000,23.101207,62312.5,5131057.314,2446.2,19807.7,36637.8
62,2021,3,16.0,2799.748387,160399.166548,57.899868,61.029073,41.411106,72.166095,133.990362,...,44.221818,25.568000,76.970000,133.610000,16.184404,86792.2,4972374.163,3507.4,31070.4,50069.3
63,2021,4,15.5,2716.390000,162245.425200,64.228906,80.093472,39.906879,91.596735,190.984750,...,56.354286,30.873750,115.050000,131.640000,24.710161,81491.7,4867362.756,2346.9,26604.3,50809.7

In [10]:
monthly.to_csv('dam_monthly.csv')