In [1]:
import numpy as np
import pandas as pd

In [14]:
data = pd.read_csv("power_energy.csv")
data['Date']=pd.to_datetime(data['Date'],format="%d/%m/%Y")
data=data.set_index(pd.DatetimeIndex(data['Date']))
data=data.drop(['Date'],axis=1)
data

,Inflow,Headpond_Level,Headloss_left_Channel,Headloss_in_Canal,Reservoir_Level,EFlow_Exceedance,CA_EFlow,CC_EFlow,CD_EFlow,CE_EFlow,...,Spill_Flow,Tailwater_level,Net_head,T1_Power,T2_Power,T3_Power,T4_Power,Total_Power,Energy,Cap_Factor_Pct
Date,,,,,,,,,,,,,,,,,,,,,
1924-10-01,111.41,990.0,0.06,0.0,989.94,0.50,37,5,3,2,...,14.41,964.5,25.44,0.00,0.0,0.0,0.0,0.00,0.00,0.00
1924-10-02,111.41,990.0,0.06,0.0,989.94,0.50,37,5,3,2,...,14.41,964.5,25.44,0.00,0.0,0.0,0.0,0.00,0.00,0.00
1924-10-03,111.41,990.0,0.06,0.0,989.94,0.50,37,5,3,2,...,14.41,964.5,25.44,0.00,0.0,0.0,0.0,0.00,0.00,0.00
1924-10-04,111.41,990.0,0.06,0.0,989.94,0.50,37,5,3,2,...,14.41,964.5,25.44,0.00,0.0,0.0,0.0,0.00,0.00,0.00
1924-10-05,111.41,990.0,0.06,0.0,989.94,0.50,37,5,3,2,...,14.41,964.5,25.44,0.00,0.0,0.0,0.0,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-09-26,200.67,990.0,0.09,0.0,989.91,0.82,34,6,4,3,...,0.00,964.4,25.42,23.59,0.0,0.0,0.0,23.59,566.05,0.12
2017-09-27,200.67,990.0,0.09,0.0,989.91,0.82,34,6,4,3,...,0.00,964.4,25.42,23.59,0.0,0.0,0.0,23.59,566.05,0.12
2017-09-28,200.67,990.0,0.09,0.0,989.91,0.82,34,6,4,3,...,0.00,964.4,25.42,23.59,0.0,0.0,0.0,23.59,566.05,0.12
2017-09-29,200.67,990.0,0.09,0.0,989.91,0.82,34,6,4,3,...,0.00,964.4,25.42,23.59,0.0,0.0,0.0,23.59,566.05,0.12
2017-09-30,200.01,990.0,0.09,0.0,989.91,0.82,34,6,4,3,...,0.00,964.4,25.43,23.42,0.0,0.0,0.0,23.42,562.19,0.12